project:
  type: website
  output-dir: docs

website:
  title: "Good Enough Lab"
  navbar:
    left: 
      - text: Development Blog
        href: blog.qmd
        menu:
          - text: Cave - 2025-03-20
            href: blog/2025-03-20-cave.qmd
          - text: Login - 2025-03-19
            href: blog/2025-03-18.qmd
          - text: Phone - 2025-03-17
            href: blog/2025-03-17-button.qmd
          - text: Button - 2025-03-15
            href: blog/2025-03-15-button.qmd
          - text: Button - 2025-03-14
            href: blog/2025-03-14-button.qmd
      - text: Drafts
        menu:
          - text: Singularities
            href: singularities.qmd
          - text: Singularities in Pop Culture
            href: pop.qmd
          - text: Questionable Analytical Observations
            href: qao.qmd
    right:
      - text: Collaborate
        href: collab.qmd
      - text: Lab
        href: lab.qmd
      - text: Values
        href: values.qmd

format:
  html:
    html-math-method: mathml
    theme: 
      - superhero
    font:
      heading: "courier"
      body: "courier"
    css: styles.css
    toc: true
