project:
  type: website
  output-dir: docs
  execute-dir: project
  resources:
    - img/subprime.pdf

website:
  title: "Good Enough Lab"
  favicon: good-enough-logo.png

  navbar:
    logo: good-enough-logo.png
    left:
      - text: Consulting
        menu:
          - text: Consulting
            href: consulting/consulting.qmd
          - text: ESG
            href: consulting/esg.qmd
          - text: Research 
            href: research/research.qmd
          - text: Development Blog
            href: blog.qmd
      - text: Ethics
        href: consulting/trauma.qmd
    right:
      - text: Lab
        href: lab.qmd
      - text: Work with us
        href: collab.qmd
      - text: Values
        href: values.qmd

format:
  html:
    html-math-method: mathml
    theme: 
      - superhero
    font:
      heading: "courier"
      body: "courier"
    css: styles.css
    toc: true
