project:
  type: website
  output-dir: docs

website:
  title: "Good Enough Lab"
  navbar:
    left: 
      - menu: 
        - text: Singularities
          href: singularities-placeholder.qmd
        - text: Button
          href: button.qmd
        - text: Singularities as Math
          href: math.qmd
        - text: Singularities in Pop Culture
          href: pop.qmd
        - text: Questionable Analytical Observations
          href: qao.qmd
    right:
      - text: Collaborate
        href: collab.qmd
      - text: Lab
        href: lab.qmd
      - text: Values
        href: values.qmd

format:
  html:
    theme: 
      - superhero
    font:
      heading: "courier"
      body: "courier"
    css: styles.css
    toc: true