project:
  type: website
  output-dir: docs

website:
  title: "Good Enough Lab"
  navbar:
    left: 
      - text: Singularities
        href: singularities.qmd
      - text: Questionable Analytical Observations
        href: qao.qmd
      - text: Singularities in Pop Culture
        href: pop.qmd
    right:
      - text: Collaborate
        href: collab.qmd
      - text: Lab
        href: lab.qmd
      - text: Values
        href: values.qmd

format:
  html:
    theme: 
      - superhero
    font:
      heading: "courier"
      body: "courier"
    css: styles.css
    toc: true