---
title: A singularity of button

---


# The button problem


## Emotional wellbeing

As a human, I feel overwhelmed.

I have the right skills to do the agile thing.


```
Think of agile like this. 

Leadership: Mirror, mirror on  the  wall, who has the FAIRest vision of them all?

Product managers smash the mirror into pieces.

Developers smash those pieces into shards.

Different developers paint the shards in tiny ways to make the vision FAIR.

Developers reassemble shards into pieces.

Product managers reassemble those pieces into the mirror painted to leadership's vision.

Leadership: Mirror, mirror on the wall, forget FAIR, I can't see my fucking face at all.

```

I can see why there was a breakdown between humans. I can see how cultural difference come into play.

But why is there an analogous breakdown for me? 

Why do I feel like the greater my computational projects scale, the greater the anxiety? Why does nothing ever go as it should?

It's the *not knowing* that drives me crazy. If I could just know what I know, at least see what the bounds of knowledge of this system is, I think I would feel less overwhelmed.

The answer is in chaos and category theory. Let's go. Freeform. 

# Singularities within the button problem

- button visualisatons
- formatting across slides and manuscript did not work
- game
- slides
- manuscript

# Button characteristics

These are all supported by the button package. 

Fundamentally, there's something to be learnt from the music project.

## What went wrong? 

Assumption as a graph.

::: {.panel-tabset}

## edges 

It always starts with edges.

```{r}
library(tidyverse)

tribble(
  ~from,    ~to,
  "raw",    "edges",
  "edges",  "nodes",
  "df",     "tidygraph",
  "raw",    "nodes",
  "edges",  "tidygraph",
  "nodes",  "tidygraph",
  "tidygraph", "ggraph",
  "ggraph",   "production"
)



```

:::