---
title: "Good Enough People"
---

[**Dr Charles T. Gray, Data Punk**](https://www.linkedin.com/in/charles-t-gray/), founder of Good Enough Data & Systems Lab, is often described as a force of nature in data, not always in a good way. She is a data punk who speaks truth of corrupt data to power.  Her survivor identity is core to ethics of Good Enough Data & Systems Lab.

Charles makes connections others don't using a framework of algebra, cultural studies, and more; her polymathic reasoning and ability to conceptualise abstract concepts has become socially awkward in traditional job descriptions. 

Especially when everyone else is ignoring garbage data.

## A reluctanct career move

All Charles has ever wanted was a steady, fun job.

Charles fell into music at 17, when her piano teacher discvored she was living in a housing program for homeless youth. She found this a good way to  

## Good enough to be worthwhile

Charles has always struggled with a sense a sense of not being good enough. Through decades of therapy, courses, and reading, she has come to understand how the abandonment melange (cite pete walker) cemented in her turbulent adolesce has been exacerabated by the consant innovation of the data industry. 

She believes there should be spaces safe for those who do not fit traditional roles and bring much-needed innovation through diverse perspectives. 

She has never found a space where it's good enough to love math and code as trauma therapy, so she has created the Good Enough Lab to create an oasis for the neurospicy in data, where everyone is good enough. 

## Mathematics as trauma therapy

Charles manages her trauma by having good enough problems to solve; this enables her to good into a flowstate where her traumatic memories cannot touch her. 

This is her super power, it is not her weakness. Trauma has not only given Charles a masterclass in inclusivity and empathy, and, not only that, her unique scientific reasoning is has further traumatised her, as she has spent a career fending off unconscious microagressions from people's insecurity when they cannot follow her reasoning.  