---
title: "Good Enough Data & Systems Lab"
subtitle: "Structured Intelligence Governance"
html-math-method: mathml
---

> *Order from the chaos of development.*

---

We are the piano accompanists of science.

A collective of systems epistemologists, engineers, and scientists asking:

> **How can society use computational tools more intelligently?**

The Lab was founded by Dr Charles T. Gray, a senior data science architect, to design ethical, adaptable, and intelligent infrastructure for inquiry.

→ [Our values](values.qmd)

---


## Research

We work voluntarily with Systemic Injustice Research Partners to build better science.

**Applied**  
→ Conservation strategy and epistemic justice in the Global South  

**Theoretical**  
→ Formalising injustice in code  
→ Designing data architecture at the intersection of critical theory and category theory

→ [Learn more about our Good Enough publications](research/research.qmd)


---

## Industry Partners

We partner with data science and modern data stack tool developers to demonstrate features they want users to know about. 

We build our demonstrations using open science research collaborations with Systemic Injustice Research Partners, serving a dual purpose of amplifying anlaytics the world needs to see.

→ [Partner with the Good Enough Lab](collab.qmd)

---

## Consulting

> *It ain't what you don't know that gets you into trouble. It's what you know for sure that just ain't so.*  

We help organisations design data systems at scale that are FAIR to the humans inside them.

Our consulting services bring test-driven migration, inclusive automation, and change management strategies grounded in broad experience of computational epistemology.

→ [Explore our services](consulting/consulting.qmd)

---

## ESG & Epistemic Integrity

The Lab works with enterprise and public institutions to build structured intelligence systems that meet ESG demands without sacrificing traceability or trust.

We don’t do checkbox compliance.  
We engineer systems at scale that make sustainability claims *auditable, semantic, and human-aligned*.

→ [Learn more about ESG-aligned system design](consulting/esg.qmd)

